# https://taskfile.dev

version: "3"

env:
  CGO_ENABLED: "0"

tasks:
  default:
    cmds:
      - task: run

  run:
    cmds:
      - go run cmd/parrot/main.go {{.CLI_ARGS}}

  build:
    cmds:
      - |
        {{ $os := .GOOS | default OS }}
        {{ $arch := .GOARCH | default ARCH }}
        GOOS={{$os}} GOARCH={{$arch}} go build -o {{.OUT_DIR | default (print "bin/parrot_" $os "_" $arch exeExt) }} cmd/parrot/main.go

  build-dpkg:
    aliases:
      - dpkg
    requires:
      vars:
        - GOARCH
    deps:
      - task: build
        vars:
          GOOS: "linux"
          GOARCH: "{{ .GOARCH }}"
          OUT_DIR: dist/dpkg/usr/local/bin/parrot
    cmds:
      - scripts/build-dpkg-package.sh {{.GOARCH}}
      - defer: git checkout dist/dpkg
      - defer: rm -r dist/dpkg/usr/local/bin
