name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set Asset Path
        if: ${{ matrix.goos == 'windows' }}
        shell: bash
        run: echo "ASSET_PATH=./bin/parrot-${{ matrix.goos }}-${{ matrix.goarch }}.exe" >> $GITHUB_ENV
      - name: Set Asset Path
        if: ${{ matrix.goos != 'windows' }}
        shell: bash
        run: echo "ASSET_PATH=./bin/parrot-${{ matrix.goos }}-${{ matrix.goarch }}" >> $GITHUB_ENV
      - name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o ${{ env.ASSET_PATH }} ./cmd/parrot/main.go
      - name: Upload Artifcats
        if: ${{ matrix.goos != 'linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.goarch }}
          path: ${{ env.ASSET_PATH }}
          retention-days: 1
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_dpkg:
    name: Build DPKG Packages
    runs-on: ubuntu-latest
    needs:
      - build_artifacts
    strategy:
      matrix:
        goarch:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieve backend binaries
        uses: actions/download-artifact@v4
        with:
          name: artifacts-${{ matrix.target }}
          path: dist/dpkg/usr/local/bin
      - name: Rename binary
        run: |
          mv dist/dpkg/usr/local/bin/parrot* dist/dpkg/usr/local/bin/parrot
          chmod +x dist/dpkg/usr/local/bin/parrot
      - name: Build dpkg package
        run: bash ./scripts/build-dpkg-package.sh ${{ matrix.goarch }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: parrot-*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
